import { auth, db, storage, ADMIN_EMAIL } from './firebase-config.js';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-auth.js';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, orderBy, query, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-firestore.js';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-storage.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
let products=[], gallery=[], orders=[], settings={}, active='Dashboard', editing=null;
const LS_PRODUCTS='cf_products_local', LS_GALLERY='cf_gallery_local', LS_SETTINGS='cf_settings_local', LS_ORDERS='cf_orders_local';
const LS_GALLERY_INITIALIZED='cf_gallery_initialized';
const DEFAULT_GALLERY=[
'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1603217040830-34473db521a7?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85',
'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1000&q=85',
'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1000&q=85',
'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=85'
];
function ensureLocalGallery(){if(localStorage.getItem(LS_GALLERY_INITIALIZED)!=='1'){const existing=localJSON(LS_GALLERY,[]);if(!existing.length){saveLocal(LS_GALLERY,DEFAULT_GALLERY.map((image,i)=>({id:'local-g-'+i,image,sortOrder:i,createdAt:new Date().toISOString(),local:true})));}localStorage.setItem(LS_GALLERY_INITIALIZED,'1')}}
const localJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}; const saveLocal=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const cats=['Sarees','Kurtis','Dresses','Kids Wear',"Men's Wear",'School Uniform','New Arrival'];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
const LOCAL_ADMIN_EMAIL = 'admin@chandrakala.com';
const LOCAL_ADMIN_PASSWORD = 'Chandra@1234';
const LOCAL_SESSION_KEY = 'chandrakala_admin_session';
function login(){document.body.innerHTML=`<div id="toast" class="toast"></div><div class="login-wrap"><div class="login-card"><div class="eyebrow">CHANDRAKALA FASHION</div><h1 style="font:700 42px Georgia,serif;margin:8px 0">Admin portal</h1><p class="muted">Private management area. Customers never see this page.</p><div class="field"><label>Admin ID</label><input id="email" value="${LOCAL_ADMIN_EMAIL}" autocomplete="username"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="Enter admin password" autocomplete="current-password"></div><button class="btn" style="width:100%" id="loginBtn">Sign in</button><p class="notice" style="margin-top:15px">Demo/local admin login. Use the credentials supplied with this package.</p></div></div>`;const submit=()=>{const email=$('#email').value.trim().toLowerCase(),pw=$('#password').value;if(email===LOCAL_ADMIN_EMAIL && pw===LOCAL_ADMIN_PASSWORD){localStorage.setItem(LOCAL_SESSION_KEY,'1');location.reload()}else toast('Invalid Admin ID or password')};$('#loginBtn').onclick=submit;$('#password').addEventListener('keydown',e=>{if(e.key==='Enter')submit()})}
async function load(){ensureLocalGallery();const lp=localJSON(LS_PRODUCTS,[]),lg=localJSON(LS_GALLERY,[]),lo=localJSON(LS_ORDERS,[]),ls=localJSON(LS_SETTINGS,{});try{products=(await getDocs(collection(db,'products'))).docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>(x.sortOrder??99999)-(y.sortOrder??99999));if(!products.length)products=lp}catch{products=lp}gallery=lg.slice().sort((x,y)=>(x.sortOrder??99999)-(y.sortOrder??99999));try{const remote=(await getDocs(collection(db,'orders'))).docs.map(d=>({id:d.id,...d.data()}));orders=[...lo,...remote.filter(o=>!lo.some(x=>x.id===o.id))].sort((x,y)=>String(y.createdAt?.seconds||y.createdAt||'').localeCompare(String(x.createdAt?.seconds||x.createdAt||'')))}catch{orders=lo}try{const s=await getDocs(collection(db,'settings'));settings={...ls,...(s.docs.find(d=>d.id==='store')?.data()||{})}}catch{settings=ls}render()}
function render(){document.body.innerHTML=`<div class="admin-shell"><header class="admin-top"><div><b>Chandrakala Fashion</b><span style="opacity:.6;margin-left:10px">Admin</span></div><div style="display:flex;gap:8px"><a class="btn light" href="index.html">View Store</a><button class="btn gold" id="logout">Sign out</button></div></header><div class="admin-main"><aside class="admin-side">${['Dashboard','Products','Gallery','Orders','Payments','Settings'].map(t=>`<button class="admin-tab ${active===t?'active':''}" data-tab="${t}">${t}</button>`).join('')}</aside><main class="admin-content"><div id="panel"></div></main></div></div><div id="toast" class="toast"></div>`;$('#logout').onclick=()=>{localStorage.removeItem(LOCAL_SESSION_KEY);location.reload()};$$('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;render()});panel();}
function panel(){const p=$('#panel');if(active==='Dashboard')p.innerHTML=dashboard();if(active==='Products')p.innerHTML=productsPanel();if(active==='Gallery')p.innerHTML=galleryPanel();if(active==='Orders')p.innerHTML=ordersPanel();if(active==='Payments')p.innerHTML=paymentsPanel();if(active==='Settings')p.innerHTML=settingsPanel();bindPanel()}
function dashboard(){const revenue=orders.filter(o=>o.status==='Paid'||o.status==='Completed').reduce((s,o)=>s+Number(o.total||0),0);return `<div class="eyebrow">CONTROL CENTRE</div><h1 style="font:700 46px Georgia,serif;margin:8px 0">Store dashboard</h1><p class="muted">Everything important is managed from here.</p><div class="stat-grid"><div class="stat-card"><span class="muted">Products</span><br><b>${products.length}</b></div><div class="stat-card"><span class="muted">Gallery photos</span><br><b>${gallery.length}</b></div><div class="stat-card"><span class="muted">Orders</span><br><b>${orders.length}</b></div><div class="stat-card"><span class="muted">Paid revenue</span><br><b>${money(revenue)}</b></div></div><div class="admin-card"><h2>Admin checklist</h2><p class="muted">✓ Product add/edit/delete & image upload<br>✓ Gallery upload/delete/reorder<br>✓ Order status management<br>✓ Razorpay/UPI/COD configuration<br>✓ Store contact/settings</p></div>`}
function productsPanel(){return `<div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><div class="eyebrow">CATALOGUE</div><h1 style="font:700 40px Georgia,serif">Products</h1></div><button class="btn" id="newProduct">+ Add product</button></div><div class="admin-card">${products.length?`<table class="admin-table"><thead><tr><th>Image</th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${products.map(p=>`<tr><td><img class="admin-thumb" src="${p.image||''}"></td><td><b>${p.name}</b></td><td>${p.category||''}</td><td>${money(p.price)}</td><td>${p.stock||''}</td><td><div class="row-actions"><button class="small-btn" data-edit="${p.id}">Edit</button><button class="small-btn danger" data-del="${p.id}">Delete</button></div></td></tr>`).join('')}</tbody></table>`:'<div class="notice">No products yet. Add your first product.</div>'}</div>`}
function productForm(p={name:'',category:cats[0],price:'',stock:'In Stock',image:''}){openModal(`<h2>${editing?'Edit':'Add'} product</h2><div class="field"><label>Product name</label><input id="pn" value="${esc(p.name)}"></div><div class="form-grid"><div class="field"><label>Category</label><select id="pc">${cats.map(c=>`<option ${c===p.category?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Price (INR)</label><input id="pp" type="number" value="${p.price||''}"></div></div><div class="field"><label>Stock label</label><input id="ps" value="${esc(p.stock||'In Stock')}"></div><div class="field"><label>Product image</label><input id="pi" value="${esc(p.image||'')}" placeholder="Image URL or upload below"><input id="pif" type="file" accept="image/*"></div><div class="actions"><button class="btn" id="saveP">Save product</button><button class="btn light" id="cancelM">Cancel</button></div>`);$('#cancelM').onclick=closeModal;$('#saveP').onclick=async()=>{try{let image=$('#pi').value.trim();const file=$('#pif').files[0];if(file){image=await uploadFile(file,'products')}if(!image)throw Error('Please add an image URL or upload an image.');const data={name:$('#pn').value.trim(),category:$('#pc').value,price:Number($('#pp').value),stock:$('#ps').value.trim(),image,updatedAt:serverTimestamp()};if(editing){try{await updateDoc(doc(db,'products',editing),data)}catch{}products=products.map(x=>x.id===editing?{...x,...data}:x)}else{let id='local-p-'+Date.now();try{const d=await addDoc(collection(db,'products'),{...data,sortOrder:products.length,createdAt:serverTimestamp()});id=d.id}catch{}products=[...products,{id,...data,sortOrder:products.length,local:true}]}saveLocal(LS_PRODUCTS,products);closeModal();await load();toast('Product saved')}catch(e){toast(e.message)}}}
function galleryPanel(){return `<div style="display:flex;justify-content:space-between;align-items:center"><div><div class="eyebrow">VISUAL CONTENT</div><h1 style="font:700 40px Georgia,serif">Gallery</h1></div><button class="btn" id="uploadGallery">+ Upload photos</button></div><div class="admin-card"><div class="notice">Drag order controls with ↑ ↓. Delete removes the gallery record and the uploaded Firebase Storage file.</div><div class="gallery-admin" style="margin-top:16px">${gallery.map((g,i)=>`<div class="gallery-admin-item"><img src="${g.image}"><div style="font-size:12px;margin:8px 0"><b>#${i+1}</b></div><div class="row-actions"><button class="small-btn" data-up="${g.id}">↑</button><button class="small-btn" data-down="${g.id}">↓</button><button class="small-btn danger" data-gdel="${g.id}">Delete</button></div></div>`).join('')}</div></div>`}
function ordersPanel(){return `<div class="eyebrow">SALES</div><h1 style="font:700 40px Georgia,serif">Orders</h1><div class="admin-card">${orders.length?`<table class="admin-table"><thead><tr><th>Customer</th><th>Total</th><th>Payment</th><th>Address</th><th>Status</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${esc(o.customer||'Customer')}</b><br>${esc(o.phone||'')}</td><td>${money(o.total)}</td><td>${esc(o.payment||'')}</td><td>${esc(o.address||'')}</td><td><select data-status="${o.id}">${['New','Payment Pending','Paid','Packed','Out for Delivery','Completed','Cancelled'].map(s=>`<option ${s===(o.status||'New')?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>`:'<div class="notice">No orders yet.</div>'}</div>`}
function paymentsPanel(){return `<div class="eyebrow">CHECKOUT</div><h1 style="font:700 40px Georgia,serif">Payment Gateway</h1><div class="admin-card"><h2>UPI + QR Payments</h2><p class="muted">Set the store UPI ID once. Checkout will create a QR code and a UPI-app payment link. Customers can use Google Pay, PhonePe, Paytm or another UPI app supported by their phone.</p><div class="field"><label>UPI ID</label><input id="upi" value="${esc(settings.upiId||'')}" placeholder="yourbusiness@upi"></div><div class="field"><label>Enable UPI / QR</label><select id="upiEnabled"><option value="false">Disabled</option><option value="true" ${settings.upiEnabled!==false?'selected':''}>Enabled</option></select></div><h2 style="margin-top:24px">Razorpay</h2><div class="field"><label>Enable Razorpay</label><select id="payEnabled"><option value="false">Disabled</option><option value="true" ${settings.paymentEnabled?'selected':''}>Enabled</option></select></div><div class="field"><label>Razorpay Key ID (public)</label><input id="razorKey" value="${esc(settings.razorpayKeyId||'')}" placeholder="rzp_test_... or rzp_live_..."></div><button class="btn" id="savePay">Save payment settings</button><div class="notice" style="margin-top:16px"><b>Payment note:</b> UPI/QR is direct payment to your UPI ID. The website cannot independently verify that payment unless you use a payment gateway with server-side verification. Razorpay can provide automatic verification when its secure backend is configured.</div></div>`}
function settingsPanel(){return `<div class="eyebrow">STORE PROFILE</div><h1 style="font:700 40px Georgia,serif">Settings</h1><div class="admin-card"><div class="field"><label>Store name</label><input id="storeName" value="${esc(settings.storeName||'Chandrakala Fashion')}"></div><div class="field"><label>Phone</label><input id="storePhone" value="${esc(settings.phone||'+91 93700 17895')}"></div><div class="field"><label>Address</label><textarea id="storeAddress" rows="3">${esc(settings.address||'1500, Agra Rd, Navnath Nager, Dhule, Maharashtra 424001')}</textarea></div><div class="field"><label>WhatsApp number (digits only)</label><input id="wa" value="${esc(settings.whatsapp||'919370017895')}"></div><button class="btn" id="saveSettings">Save store settings</button></div>`}
function bindPanel(){if($('#newProduct'))$('#newProduct').onclick=()=>{editing=null;productForm()};$$('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;productForm(products.find(p=>p.id===editing))});$$('[data-del]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del));if($('#uploadGallery'))$('#uploadGallery').onclick=galleryUpload;$$('[data-gdel]').forEach(b=>b.onclick=()=>deleteGallery(b.dataset.gdel));$$('[data-up]').forEach(b=>b.onclick=()=>moveGallery(b.dataset.up,-1));$$('[data-down]').forEach(b=>b.onclick=()=>moveGallery(b.dataset.down,1));$$('[data-status]').forEach(s=>s.onchange=async()=>{const id=s.dataset.status;try{await updateDoc(doc(db,'orders',id),{status:s.value})}catch{}orders=orders.map(o=>o.id===id?{...o,status:s.value}:o);saveLocal(LS_ORDERS,orders);toast('Order status updated')});if($('#savePay'))$('#savePay').onclick=savePayment;if($('#saveSettings'))$('#saveSettings').onclick=saveSettings}
async function galleryUpload(){openModal(`<h2>Upload gallery photos</h2><p class="muted">Select one or more images. They are stored locally for this admin/store demo and can be deleted or reordered here.</p><div class="field"><input id="gf" type="file" accept="image/*" multiple></div><button class="btn" id="gup">Upload</button>`);$('#gup').onclick=async()=>{const files=[...$('#gf').files];if(!files.length)return toast('Select at least one image');try{for(const file of files){const image=await fileToDataURL(file);gallery.push({id:'local-g-'+Date.now()+'-'+Math.random().toString(36).slice(2),image,sortOrder:gallery.length,createdAt:new Date().toISOString(),local:true})}gallery=gallery.map((g,i)=>({...g,sortOrder:i}));saveLocal(LS_GALLERY,gallery);localStorage.setItem(LS_GALLERY_INITIALIZED,'1');closeModal();await load();toast(`${files.length} gallery photo${files.length>1?'s':''} uploaded`)}catch(e){toast(e.message)}}}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}

async function uploadFile(file,folder){const safe=`${Date.now()}-${Math.random().toString(36).slice(2)}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const r=ref(storage,`${folder}/${safe}`);await uploadBytes(r,file);return getDownloadURL(r)}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;try{try{await deleteDoc(doc(db,'products',id))}catch{}products=products.filter(x=>x.id!==id).map((x,i)=>({...x,sortOrder:i}));saveLocal(LS_PRODUCTS,products);await load();toast('Product deleted')}catch(e){toast(e.message)}}
async function deleteGallery(id){if(!confirm('Delete this gallery photo?'))return;gallery=gallery.filter(x=>x.id!==id).map((x,i)=>({...x,sortOrder:i}));saveLocal(LS_GALLERY,gallery);localStorage.setItem(LS_GALLERY_INITIALIZED,'1');await load();toast('Gallery photo deleted')}
async function moveGallery(id,delta){const i=gallery.findIndex(g=>g.id===id),j=i+delta;if(i<0||j<0||j>=gallery.length)return;[gallery[i],gallery[j]]=[gallery[j],gallery[i]];gallery=gallery.map((g,k)=>({...g,sortOrder:k}));saveLocal(LS_GALLERY,gallery);render();toast('Gallery order updated')}
async function savePayment(){settings={...settings,paymentEnabled:$('#payEnabled').value==='true',upiEnabled:$('#upiEnabled').value==='true',razorpayKeyId:$('#razorKey').value.trim(),upiId:$('#upi').value.trim()};saveLocal(LS_SETTINGS,settings);try{await setDoc(doc(db,'settings','store'),settings)}catch{}toast('Payment settings saved')}
async function saveSettings(){settings={...settings,storeName:$('#storeName').value.trim(),phone:$('#storePhone').value.trim(),address:$('#storeAddress').value.trim(),whatsapp:$('#wa').value.trim()};saveLocal(LS_SETTINGS,settings);try{await setDoc(doc(db,'settings','store'),settings)}catch{}toast('Store settings saved')}
function openModal(html){let m=document.createElement('div');m.id='modal';m.className='modal';m.innerHTML=`<div class="modal-card">${html}</div>`;document.body.appendChild(m)}function closeModal(){$('#modal')?.remove()}function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
if(localStorage.getItem(LOCAL_SESSION_KEY)==='1') load(); else login();
