import { auth, db } from './firebase-config.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-functions.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-auth.js';
import { collection, getDocs, addDoc, query, orderBy, where, serverTimestamp, doc, getDoc } from 'https://www.gstatic.com/firebasejs/11.0.0/firebase-firestore.js';

const PHONE='919370017895', ADDRESS='1500, Agra Rd, Navnath Nager, Dhule, Maharashtra 424001';
const fallbackProducts=[
['Banarasi Silk Saree','Sarees',2499,'In Stock','https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85'],
['Designer Cotton Kurti','Kurtis',799,'In Stock','https://images.unsplash.com/photo-1603217040830-34473db521a7?auto=format&fit=crop&w=900&q=85'],
['Premium Party Dress','Dresses',1299,'Limited','https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85'],
['Kids Festive Set','Kids Wear',699,'In Stock','https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=85'],
['Smart School Uniform','School Uniform',599,'In Stock','https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=900&q=85'],
['Latest Co-ord Set','New Arrival',1099,'New','https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85'],
['Chanderi Saree','Sarees',1899,'In Stock','https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=85'],
['Printed Rayon Kurti','Kurtis',649,'In Stock','https://images.unsplash.com/photo-1603252109360-909baaf261c7?auto=format&fit=crop&w=900&q=85'],
['Floral Gown','Dresses',1599,'Limited','https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85']
].map((p,i)=>({id:'demo-'+i,name:p[0],category:p[1],price:p[2],stock:p[3],image:p[4]}));
const fallbackGallery=[...fallbackProducts.slice(0,6).map(p=>p.image),'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=85'];
let products=[],gallery=[],cart=JSON.parse(localStorage.getItem('cf_cart')||'[]'), user=null, page='home', storeSettings={};
const functions=getFunctions();
const $=s=>document.querySelector(s); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function wa(product=''){return `https://wa.me/${PHONE}?text=${encodeURIComponent(product?`Hello Chandrakala Fashion, I am interested in ${product}.`:'Hello Chandrakala Fashion, I want to explore your collection.')}`}
async function load(){try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.sortOrder??99999)-(b.sortOrder??99999));if(!products.length) products=fallbackProducts}catch{products=fallbackProducts}try{const snap=await getDocs(collection(db,'gallery'));gallery=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.sortOrder??99999)-(b.sortOrder??99999));if(!gallery.length)gallery=fallbackGallery.map((image,i)=>({id:'g'+i,image,sortOrder:i}))}catch{gallery=fallbackGallery.map((image,i)=>({id:'g'+i,image,sortOrder:i}))}try{const s=await getDocs(collection(db,'settings'));storeSettings=s.docs.find(d=>d.id==='store')?.data()||{}}catch{storeSettings={}}render()}
function header(){return `<div class="topbar">FREE LOCAL DELIVERY ON SELECT ORDERS • DHULE, MAHARASHTRA</div><header class="nav"><div class="container nav-inner"><a class="brand" href="#home">Chandrakala<small>FASHION • DHULE</small></a><nav class="nav-links"><a href="#home">Home</a><a href="#collections">Collections</a><a href="#gallery">Gallery</a><a href="#about">About</a><a href="#contact">Contact</a></nav><div class="nav-actions"><button class="icon-btn mobile-toggle" id="mobileMenuBtn" aria-label="Open menu">☰</button><button class="icon-btn" id="accountBtn">${user?'◉':'♙'}</button><button class="icon-btn" id="cartBtn" style="position:relative">🛍<span class="cart-badge">${cart.reduce((s,x)=>s+x.qty,0)}</span></button><a class="btn gold" href="${wa()}" target="_blank">WhatsApp</a></div></div></header>`}
function render(){document.title='Chandrakala Fashion | Dhule';$('#app').innerHTML=header()+`<main>
<section class="hero"><div class="hero-copy"><div class="container"><div class="eyebrow">CHANDRAKALA FASHION</div><h1>Everyday elegance. Made for every occasion.</h1><p>Discover sarees, kurtis, dresses, kids wear, men's wear and school uniforms — thoughtfully selected for Dhule families.</p><div class="actions"><a class="btn" href="#collections">Shop Collection</a><a class="btn light" href="${wa()}" target="_blank">Talk on WhatsApp</a></div></div></div><div class="hero-photo"></div></section>
<section class="section" id="collections"><div class="container"><div class="section-head"><div><div class="eyebrow">CURATED FOR YOU</div><h2>Shop by collection</h2></div><span class="muted">${products.length}+ styles online</span></div><div class="categories">${categoryCards()}</div></div></section>
<section class="section" style="background:#f2f0eb"><div class="container"><div class="section-head"><div><div class="eyebrow">NEW & LOVED</div><h2>Featured pieces</h2></div><button class="small-btn" id="viewAll">View all</button></div><div class="products">${products.slice(0,6).map(productCard).join('')}</div></div></section>
<section class="section" id="gallery"><div class="container"><div class="section-head"><div><div class="eyebrow">THE CHANDRAKALA EDIT</div><h2>Inside the store</h2></div></div><div class="gallery-grid">${gallery.slice(0,9).map((g,i)=>`<div class="gallery-item" data-gallery="${i}"><img src="${g.image}" alt="Chandrakala Fashion gallery ${i+1}" loading="lazy"></div>`).join('')}</div></div></section>
<section class="section" id="about"><div class="container story"><div class="story-img"></div><div class="story-copy"><div class="eyebrow">OUR STORY</div><h2>Fashion that feels personal.</h2><p>Chandrakala Fashion brings together stylish everyday wear, festive favourites and dependable school uniforms under one roof in Dhule.</p><p>Visit us in store or message us on WhatsApp for product availability, sizes and orders.</p><a class="btn" href="${wa()}" target="_blank">Chat with us</a></div></div></section>
<section class="section"><div class="container"><div class="benefits"><div class="benefit">✓<strong>Curated collections</strong><span class="muted">Styles for every occasion.</span></div><div class="benefit">✓<strong>Easy WhatsApp orders</strong><span class="muted">Ask, confirm and order quickly.</span></div><div class="benefit">✓<strong>Local support</strong><span class="muted">Real store, real people in Dhule.</span></div></div></div></section>
<section class="section" id="contact"><div class="container contact-grid"><div class="contact-card"><div class="eyebrow" style="color:#c79b53">VISIT US</div><h2>Come say hello.</h2><p>${ADDRESS}</p><p>📞 +91 93700 17895</p><div class="actions"><a class="btn gold" href="https://maps.app.goo.gl/JLybTJ3s9Bg6JMtJ9" target="_blank">Get Directions</a><a class="btn light" href="tel:+919370017895">Call</a></div></div><iframe class="map" src="https://www.google.com/maps?q=${encodeURIComponent(ADDRESS)}&output=embed" loading="lazy"></iframe></div></section>
</main><footer class="footer"><div class="container footer-grid"><div><div class="brand">Chandrakala<small style="color:#aaa">FASHION • DHULE</small></div><p>Premium fashion and uniforms for the whole family.</p></div><div><b>Explore</b><p><a href="#collections">Collections</a><br><a href="#gallery">Gallery</a><br><a href="#about">About</a></p></div><div><b>Contact</b><p>+91 93700 17895<br>Dhule, Maharashtra<br><a href="${wa()}" target="_blank">WhatsApp us</a></p></div></div></footer>${cartDrawer()}${modalContainer()}`;bind();}
function categoryCards(){const cats=[['Sarees','https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85'],['Kurtis','https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85'],['Dresses','https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85'],['Kids Wear','https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=900&q=85'],['School Uniform','https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=900&q=85'],['New Arrival','https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85']];return cats.map(c=>`<a class="category" href="#products" data-cat="${c[0]}"><img src="${c[1]}" alt="${c[0]}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=85'"><div class="overlay"><h3>${c[0]}</h3><p>Explore the latest styles →</p></div></a>`).join('')}
function productCard(p){return `<article class="product"><div class="product-img"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="tag">${p.stock||'In Stock'}</span><button class="icon-btn heart" data-wa="${p.name}">♡</button></div><div class="product-body"><div class="product-cat">${p.category||'Collection'}</div><h3>${p.name}</h3><div class="product-foot"><span class="price">${money(p.price)}</span><div><button class="small-btn" data-add="${p.id}">Add</button><a class="small-btn" style="display:inline-block" href="${wa(p.name)}" target="_blank">WhatsApp</a></div></div></div></article>`}
function cartDrawer(){return `<div class="drawer" id="cartDrawer"><div class="drawer-bg"></div><div class="drawer-panel"><div class="drawer-head"><h2>Your bag</h2><button class="icon-btn" id="closeCart">×</button></div><div id="cartRows"></div><div class="total-box"><div style="display:flex;justify-content:space-between;font-weight:900;font-size:19px"><span>Total</span><span id="cartTotal">₹0</span></div><button class="btn" style="width:100%;margin-top:15px" id="checkoutBtn">Checkout</button><a class="btn gold" style="width:100%;margin-top:8px" href="${wa()}" target="_blank">Order on WhatsApp</a></div></div></div>`}
function modalContainer(){return `<div id="modal" class="hidden"></div>`}
function bind(){
$('#cartBtn').onclick=()=>{renderCart();$('#cartDrawer').classList.add('open')};$('#closeCart').onclick=()=>$('#cartDrawer').classList.remove('open');$('#mobileMenuBtn')?.addEventListener('click',()=>{const nav=$('.nav-links');nav.classList.toggle('mobile-open')});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>$('.nav-links').classList.remove('mobile-open')));$('.drawer-bg').onclick=()=>$('#cartDrawer').classList.remove('open');$('#accountBtn').onclick=openAccount;
$$('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add);const old=cart.find(x=>x.id===p.id);old?old.qty++:cart.push({id:p.id,qty:1});saveCart();renderCart();$('#cartDrawer').classList.add('open');toast('Added to bag')});$$('[data-gallery]').forEach(x=>x.onclick=()=>openGallery(Number(x.dataset.gallery)));$('#viewAll').onclick=()=>showAll();
}
function $$(s){return [...document.querySelectorAll(s)]}
function saveCart(){localStorage.setItem('cf_cart',JSON.stringify(cart));}
function renderCart(){const rows=$('#cartRows');if(!cart.length){rows.innerHTML='<div class="notice" style="margin-top:20px">Your bag is empty. Add a product to continue.</div>';$('#cartTotal').textContent='₹0';return}rows.innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-row"><img src="${p.image}"><div><b>${p.name}</b><div class="muted">${money(p.price)}</div><div class="qty"><button data-dec="${p.id}">−</button><span>${x.qty}</span><button data-inc="${p.id}">+</button></div></div><button class="icon-btn" data-remove="${p.id}">×</button></div>`}).join('');const total=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);$('#cartTotal').textContent=money(total);$$('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));$$('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);saveCart();render();$('#cartDrawer').classList.add('open');renderCart()});$('#checkoutBtn').onclick=openCheckout}
function changeQty(id,d){const x=cart.find(x=>x.id===id);x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);saveCart();render();$('#cartDrawer').classList.add('open');renderCart()}
function openModal(html){$('#modal').className='modal';$('#modal').innerHTML=`<div class="modal-card">${html}</div>`;$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').className='hidden'};}
function openAccount(){if(user){openModal(`<div style="display:flex;justify-content:space-between"><h2>My Account</h2><button class="icon-btn" onclick="document.querySelector('#modal').className='hidden'">×</button></div><p class="muted">${user.email}</p><button class="btn" id="logoutBtn">Sign out</button><div id="ordersArea" style="margin-top:20px"></div>`);$('#logoutBtn').onclick=async()=>{await signOut(auth);toast('Signed out');document.querySelector('#modal').className='hidden'};loadOrders()}else openModal(`<h2>Customer account</h2><p class="muted">Sign in to place and track orders.</p><div class="field"><label>Email</label><input id="email"></div><div class="field"><label>Password</label><input id="pass" type="password"></div><div class="actions"><button class="btn" id="login">Sign in</button><button class="btn light" id="signup">Create account</button></div>`);$('#login').onclick=()=>authAction(false);$('#signup').onclick=()=>authAction(true)}
async function authAction(create){try{const e=$('#email').value,p=$('#pass').value;user=create?await createUserWithEmailAndPassword(auth,e,p):await signInWithEmailAndPassword(auth,e,p);document.querySelector('#modal').className='hidden';toast('Welcome back')}catch(e){toast(e.message.replace('Firebase: ','').split(' (auth')[0])}}
async function loadOrders(){try{const snap=await getDocs(query(collection(db,'orders'),where('userId','==',user.uid),orderBy('createdAt','desc')));$('#ordersArea').innerHTML='<h3>My orders</h3>'+snap.docs.map(d=>{const o=d.data();return `<div class="notice" style="margin-top:8px"><b>Order ${d.id.slice(-6)}</b> • ${money(o.total)} • ${o.status||'New'}</div>`}).join('')||'<p class="muted">No orders yet.</p>'}catch{$('#ordersArea').innerHTML='<p class="muted">No orders yet.</p>'}}
function openCheckout(){if(!cart.length)return; if(!user){$('#cartDrawer').classList.remove('open');openAccount();return}const total=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);openModal(`<h2>Checkout</h2><p class="muted">Total ${money(total)}</p><div class="form-grid"><div class="field"><label>Full name</label><input id="coName" required></div><div class="field"><label>Phone</label><input id="coPhone" value="9370017895" required></div></div><div class="field"><label>Delivery address</label><textarea id="coAddress" rows="3" required></textarea></div><div class="field"><label>Payment</label><select id="coPay"><option value="COD">Cash on Delivery</option><option value="ONLINE">Online Payment (Razorpay)</option></select></div><button class="btn" style="width:100%" id="place">Place order</button><div class="notice" style="margin-top:12px">Online payment uses the Razorpay key configured by the store admin. If it is not configured, choose Cash on Delivery.</div>`);$('#place').onclick=()=>placeOrder(total)}
async function placeOrder(total){const items=cart.map(x=>{const p=products.find(p=>p.id===x.id);return {productId:p.id,name:p.name,qty:x.qty}});const payment=$('#coPay').value;try{if(payment==='ONLINE'){if(!storeSettings.paymentEnabled||!storeSettings.razorpayKeyId)throw Error('Online payment is not enabled by the store yet. Please choose Cash on Delivery.');const createOrder=httpsCallable(functions,'createRazorpayOrder');const result=await createOrder({items,customer:$('#coName').value,phone:$('#coPhone').value,address:$('#coAddress').value});const data=result.data;await openRazorpay(data,items)}else{await addDoc(collection(db,'orders'),{userId:user.uid,customer:$('#coName').value,phone:$('#coPhone').value,address:$('#coAddress').value,items,total,payment:'COD',status:'New',createdAt:serverTimestamp()});toast('Order placed successfully');cart=[];saveCart();document.querySelector('#modal').className='hidden';render()}}catch(e){toast(e.message||'Checkout failed')}}
async function openRazorpay(data,items){await new Promise((resolve,reject)=>{if(window.Razorpay)return resolve();const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=resolve;s.onerror=()=>reject(Error('Unable to load Razorpay checkout'));document.head.appendChild(s)});const options={key:storeSettings.razorpayKeyId,amount:data.amount,currency:'INR',name:storeSettings.storeName||'Chandrakala Fashion',description:'Chandrakala Fashion order',order_id:data.razorpayOrderId,prefill:{name:$('#coName').value,email:user.email,contact:'+91'+$('#coPhone').value.replace(/\D/g,'')},theme:{color:'#111318'},handler:async response=>{try{const verify=httpsCallable(functions,'verifyRazorpayPayment');await verify({internalOrderId:data.internalOrderId,razorpayOrderId:response.razorpay_order_id,razorpayPaymentId:response.razorpay_payment_id,razorpaySignature:response.razorpay_signature});toast('Payment successful — order confirmed');cart=[];saveCart();document.querySelector('#modal').className='hidden';render()}catch(e){toast('Payment received but verification failed. Contact the store.')}}};const rzp=new window.Razorpay(options);rzp.on('payment.failed',()=>toast('Payment failed or was cancelled'));rzp.open()}
function openGallery(i){const g=gallery[i];openModal(`<div style="display:flex;justify-content:space-between;align-items:center"><h2>Chandrakala Gallery</h2><button class="icon-btn" onclick="document.querySelector('#modal').className='hidden'">×</button></div><img src="${g.image}" style="width:100%;max-height:70vh;object-fit:contain;border-radius:12px">`) }
function showAll(){openModal(`<h2>All Products</h2><div class="products" style="margin-top:18px">${products.map(productCard).join('')}</div>`);$$('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add);const old=cart.find(x=>x.id===p.id);old?old.qty++:cart.push({id:p.id,qty:1});saveCart();toast('Added to bag')})}
onAuthStateChanged(auth,u=>{user=u;render()});load();
