const PHONE='919370017895';
const ADDRESS='1500, Agra Rd, Navnath Nager, Dhule, Maharashtra 424001';
const KEYS={products:'cf_products_v3',gallery:'cf_gallery_v3',settings:'cf_settings_v3',cart:'cf_cart_v3',orders:'cf_orders_v3'};
const fallbackProducts=[
['Banarasi Silk Saree','Sarees',2499,'In Stock','https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85'],
['Designer Cotton Kurti','Kurtis',799,'In Stock','https://images.unsplash.com/photo-1603217040830-34473db521a7?auto=format&fit=crop&w=900&q=85'],
['Premium Party Dress','Dresses',1299,'Limited','https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85'],
['Kids Festive Set','Kids Wear',699,'In Stock','https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=85'],
['Smart School Uniform','School Uniform',599,'In Stock','https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=900&q=85'],
['Latest Co-ord Set','New Arrival',1099,'New','https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85'],
['Chanderi Saree','Sarees',1899,'In Stock','https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=85'],
['Printed Rayon Kurti','Kurtis',649,'In Stock','https://images.unsplash.com/photo-1603252109360-909baaf261c7?auto=format&fit=crop&w=900&q=85'],
['Floral Gown','Dresses',1599,'Limited','https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85']
].map((p,i)=>({id:'demo-'+i,name:p[0],category:p[1],price:p[2],stock:p[3],image:p[4],sortOrder:i}));
const fallbackGallery=[...fallbackProducts.slice(0,6).map(p=>p.image),'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1000&q=85','https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=85'].map((image,i)=>({id:'gallery-'+i,image,sortOrder:i,name:'Store gallery '+(i+1)}));
let products=read(KEYS.products,fallbackProducts), gallery=read(KEYS.gallery,fallbackGallery), settings=read(KEYS.settings,{storeName:'Chandrakala Fashion',phone:'+91 93700 17895',address:ADDRESS,whatsapp:PHONE,upiId:'',paymentEnabled:false}), cart=read(KEYS.cart,[]), page='home', activeCategory=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function read(k,f){try{const x=JSON.parse(localStorage.getItem(k));return x??f}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function wa(product=''){return `https://wa.me/${settings.whatsapp||PHONE}?text=${encodeURIComponent(product?`Hello Chandrakala Fashion, I am interested in ${product}.`:'Hello Chandrakala Fashion, I want to explore your collection.')}`}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function header(){return `<div class="topbar">FREE LOCAL DELIVERY ON SELECT ORDERS • DHULE, MAHARASHTRA</div><header class="nav"><div class="container nav-inner"><a class="brand" href="#home">Chandrakala<small>FASHION • DHULE</small></a><button class="icon-btn mobile-toggle" id="mobileMenu" aria-label="Menu">☰</button><nav class="nav-links"><a href="#home">Home</a><a href="#collections">Collections</a><a href="#gallery">Gallery</a><a href="#about">About</a><a href="#contact">Contact</a></nav><div class="nav-actions"><button class="icon-btn" id="accountBtn">♙</button><button class="icon-btn" id="cartBtn" style="position:relative">🛍<span class="cart-badge">${cart.reduce((s,x)=>s+x.qty,0)}</span></button><a class="btn gold" href="${wa()}" target="_blank">WhatsApp</a></div></div></header>`}
function render(){
 document.title='Chandrakala Fashion | Dhule';
 const content=page==='collection'?collectionPage(activeCategory):homePage();
 $('#app').innerHTML=header()+content+cartDrawer()+`<div id="modal" class="hidden"></div>`;
 bind();
}
function homePage(){return `<main>
<section class="hero"><div class="hero-copy"><div class="container"><div class="eyebrow">CHANDRAKALA FASHION</div><h1>Everyday elegance. Made for every occasion.</h1><p>Discover sarees, kurtis, dresses, kids wear, men's wear and school uniforms — thoughtfully selected for Dhule families.</p><div class="actions"><a class="btn" href="#collections">Shop Collection</a><a class="btn light" href="${wa()}" target="_blank">Talk on WhatsApp</a></div></div></div><div class="hero-photo"></div></section>
<section class="section" id="collections"><div class="container"><div class="section-head"><div><div class="eyebrow">CURATED FOR YOU</div><h2>Shop by collection</h2></div><span class="muted">${products.length}+ styles online</span></div><div class="categories">${categoryCards()}</div></div></section>
<section class="section" style="background:#f2f0eb"><div class="container"><div class="section-head"><div><div class="eyebrow">NEW & LOVED</div><h2>Featured pieces</h2></div><button class="small-btn" id="viewAll">View all</button></div><div class="products">${products.slice(0,6).map(productCard).join('')}</div></div></section>
<section class="section" id="gallery"><div class="container"><div class="section-head"><div><div class="eyebrow">THE CHANDRAKALA EDIT</div><h2>Inside the store</h2></div></div><div class="gallery-grid">${gallery.slice(0,9).map((g,i)=>`<div class="gallery-item" data-gallery="${i}"><img src="${g.image}" alt="Chandrakala Fashion gallery ${i+1}" loading="lazy"></div>`).join('')}</div></div></section>
<section class="section" id="about"><div class="container story"><div class="story-img"></div><div class="story-copy"><div class="eyebrow">OUR STORY</div><h2>Fashion that feels personal.</h2><p>Chandrakala Fashion brings together stylish everyday wear, festive favourites and dependable school uniforms under one roof in Dhule.</p><p>Visit us in store or message us on WhatsApp for product availability, sizes and orders.</p><a class="btn" href="${wa()}" target="_blank">Chat with us</a></div></div></section>
<section class="section"><div class="container"><div class="benefits"><div class="benefit">✓<strong>Curated collections</strong><span class="muted">Styles for every occasion.</span></div><div class="benefit">✓<strong>Easy WhatsApp orders</strong><span class="muted">Ask, confirm and order quickly.</span></div><div class="benefit">✓<strong>Local support</strong><span class="muted">Real store, real people in Dhule.</span></div></div></div></section>
<section class="section" id="contact"><div class="container contact-grid"><div class="contact-card"><div class="eyebrow" style="color:#c79b53">VISIT US</div><h2>Come say hello.</h2><p>${esc(settings.address||ADDRESS)}</p><p>📞 ${esc(settings.phone||'+91 93700 17895')}</p><div class="actions"><a class="btn gold" href="https://maps.app.goo.gl/JLybTJ3s9Bg6JMtJ9" target="_blank">Get Directions</a><a class="btn light" href="tel:${(settings.phone||'+91 93700 17895').replace(/\s/g,'')}">Call</a></div></div><iframe class="map" src="https://www.google.com/maps?q=${encodeURIComponent(settings.address||ADDRESS)}&output=embed" loading="lazy"></iframe></div></section>
</main><footer class="footer"><div class="container footer-grid"><div><div class="brand">Chandrakala<small style="color:#aaa">FASHION • DHULE</small></div><p>Premium fashion and uniforms for the whole family.</p></div><div><b>Explore</b><p><a href="#collections">Collections</a><br><a href="#gallery">Gallery</a><br><a href="#about">About</a></p></div><div><b>Contact</b><p>${esc(settings.phone||'+91 93700 17895')}<br>Dhule, Maharashtra<br><a href="${wa()}" target="_blank">WhatsApp us</a></p></div></div></footer>`}
function categoryCards(){const cats=[['Sarees','https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85'],['Kurtis','https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85'],['Dresses','https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=85'],['Kids Wear','https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?auto=format&fit=crop&w=900&q=85'],['School Uniform','https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=900&q=85'],['New Arrival','https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=85']];return cats.map(c=>`<a class="category" href="#collection" data-cat="${esc(c[0])}"><img src="${c[1]}" alt="${c[0]}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=85'"><div class="overlay"><h3>${c[0]}</h3><p>Explore the latest styles →</p></div></a>`).join('')}
function collectionPage(cat){const list=products.filter(p=>p.category===cat);return `<main><section class="section" style="padding-top:48px"><div class="container"><a class="muted" href="#collections">← Back to collections</a><div class="eyebrow" style="margin-top:26px">COLLECTION</div><div class="section-head"><div><h2>${esc(cat)}</h2><p class="muted">${list.length} styles available</p></div></div><div class="products">${list.length?list.map(productCard).join(''):'<div class="notice">No products in this collection yet.</div>'}</div></div></section></main>`}
function productCard(p){return `<article class="product"><div class="product-img"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy"><span class="tag">${esc(p.stock||'In Stock')}</span><button class="icon-btn heart" data-wa="${esc(p.name)}">♡</button></div><div class="product-body"><div class="product-cat">${esc(p.category||'Collection')}</div><h3>${esc(p.name)}</h3><div class="product-foot"><span class="price">${money(p.price)}</span><div><button class="small-btn" data-add="${p.id}">Add</button><a class="small-btn" style="display:inline-block" href="${wa(p.name)}" target="_blank">WhatsApp</a></div></div></div></article>`}
function cartDrawer(){return `<div class="drawer" id="cartDrawer"><div class="drawer-bg"></div><div class="drawer-panel"><div class="drawer-head"><h2>Your bag</h2><button class="icon-btn" id="closeCart">×</button></div><div id="cartRows"></div><div class="total-box"><div style="display:flex;justify-content:space-between;font-weight:900;font-size:19px"><span>Total</span><span id="cartTotal">₹0</span></div><button class="btn" style="width:100%;margin-top:15px" id="checkoutBtn">Checkout</button><a class="btn gold" style="width:100%;margin-top:8px" href="${wa()}" target="_blank">Order on WhatsApp</a></div></div></div>`}
function bind(){
 $('#cartBtn').onclick=()=>{renderCart();$('#cartDrawer').classList.add('open')};$('#closeCart').onclick=()=>$('#cartDrawer').classList.remove('open');$('.drawer-bg').onclick=()=>$('#cartDrawer').classList.remove('open');$('#accountBtn').onclick=openAccount;
 if($('#mobileMenu'))$('#mobileMenu').onclick=()=>{const n=$('.nav-links');n.classList.toggle('mobile-open')};
 $$('[data-cat]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;page='collection';location.hash='collection';render()});
 $$('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add);if(!p)return;const old=cart.find(x=>x.id===p.id);old?old.qty++:cart.push({id:p.id,qty:1});write(KEYS.cart,cart);renderCart();$('#cartDrawer').classList.add('open');toast('Added to bag')});
 $$('[data-gallery]').forEach(x=>x.onclick=()=>openGallery(Number(x.dataset.gallery)));
 $$('[data-wa]').forEach(x=>x.onclick=()=>window.open(wa(x.dataset.wa),'_blank'));
 if($('#viewAll'))$('#viewAll').onclick=()=>{openModal(`<h2>All Products</h2><div class="products" style="margin-top:18px">${products.map(productCard).join('')}</div>`);bindModalProducts()};
}
function bindModalProducts(){$$('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add);const old=cart.find(x=>x.id===p.id);old?old.qty++:cart.push({id:p.id,qty:1});write(KEYS.cart,cart);toast('Added to bag')})}
function renderCart(){const rows=$('#cartRows');if(!rows)return;if(!cart.length){rows.innerHTML='<div class="notice" style="margin-top:20px">Your bag is empty. Add a product to continue.</div>';$('#cartTotal').textContent='₹0';return}rows.innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);if(!p)return '';return `<div class="cart-row"><img src="${p.image}"><div><b>${esc(p.name)}</b><div class="muted">${money(p.price)}</div><div class="qty"><button data-dec="${p.id}">−</button><span>${x.qty}</span><button data-inc="${p.id}">+</button></div></div><button class="icon-btn" data-remove="${p.id}">×</button></div>`}).join('');const total=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);$('#cartTotal').textContent=money(total);$$('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));$$('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);write(KEYS.cart,cart);render();$('#cartDrawer').classList.add('open');renderCart()});$('#checkoutBtn').onclick=openCheckout}
function changeQty(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);write(KEYS.cart,cart);render();$('#cartDrawer').classList.add('open');renderCart()}
function openModal(html){$('#modal').className='modal';$('#modal').innerHTML=`<div class="modal-card">${html}</div>`;$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').className='hidden'}}
function openAccount(){openModal(`<h2>Customer account</h2><p class="muted">For this offline/local version, checkout details are saved on this browser.</p><div class="notice">You can place an order without creating an online account.</div><div class="actions"><button class="btn" id="accountClose">Close</button></div>`);$('#accountClose').onclick=()=>$('#modal').className='hidden'}
function openCheckout(){if(!cart.length)return;if(!settings.whatsapp)settings.whatsapp=PHONE;const total=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);openModal(`<h2>Checkout</h2><p class="muted">Total ${money(total)}</p><div class="form-grid"><div class="field"><label>Full name</label><input id="coName"></div><div class="field"><label>Phone</label><input id="coPhone"></div></div><div class="field"><label>Delivery address</label><textarea id="coAddress" rows="3"></textarea></div><div class="field"><label>Payment</label><select id="coPay"><option value="COD">Cash on Delivery</option><option value="UPI" ${settings.upiId?'':'disabled'}>UPI / QR Payment${settings.upiId?'':' — store has not configured UPI'}</option></select></div><div id="upiBox"></div><button class="btn" style="width:100%" id="place">Place order</button>`);$('#coPay').onchange=()=>showUpiBox(total);showUpiBox(total);$('#place').onclick=()=>placeOrder(total)}
function upiUri(total,name){return `upi://pay?pa=${encodeURIComponent(settings.upiId||'')}&pn=${encodeURIComponent(settings.storeName||'Chandrakala Fashion')}&am=${encodeURIComponent(total.toFixed(2))}&cu=INR&tn=${encodeURIComponent('Chandrakala Fashion order')}`}
function qrUrl(text){return `https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(text)}`}
function showUpiBox(total){const box=$('#upiBox');if(!box)return;if($('#coPay').value!=='UPI'){box.innerHTML='';return}box.innerHTML=`<div class="notice" style="text-align:center"><b>Scan & Pay</b><br><img src="${qrUrl(upiUri(total))}" alt="UPI QR" style="width:220px;height:220px;margin:10px auto;display:block"><div>UPI ID: <b>${esc(settings.upiId)}</b></div><a class="btn gold" href="${upiUri(total)}">Pay with UPI app</a></div>`}
function placeOrder(total){const name=$('#coName').value.trim(),phone=$('#coPhone').value.trim(),address=$('#coAddress').value.trim(),payment=$('#coPay').value;if(!name||!phone||!address)return toast('Please fill all checkout details');const order={id:'ORD-'+Date.now().toString().slice(-8),customer:name,phone,address,items:cart.map(x=>{const p=products.find(p=>p.id===x.id);return {productId:p.id,name:p.name,qty:x.qty,price:p.price}}),total,payment,status:payment==='UPI'?'Payment Pending':'New',createdAt:new Date().toISOString()};const orders=read(KEYS.orders,[]);orders.unshift(order);write(KEYS.orders,orders);const msg=`Hello Chandrakala Fashion, I placed order ${order.id}. Total: ${money(total)}. Name: ${name}. Phone: ${phone}.`;cart=[];write(KEYS.cart,cart);$('#modal').className='hidden';render();toast('Order saved successfully');setTimeout(()=>window.open(`https://wa.me/${settings.whatsapp||PHONE}?text=${encodeURIComponent(msg)}`,'_blank'),250)}
function openGallery(i){const g=gallery[i];if(!g)return;openModal(`<div style="display:flex;justify-content:space-between;align-items:center"><h2>Chandrakala Gallery</h2><button class="icon-btn" id="closeGallery">×</button></div><img src="${g.image}" style="width:100%;max-height:70vh;object-fit:contain;border-radius:12px">`);$('#closeGallery').onclick=()=>$('#modal').className='hidden'}
window.addEventListener('hashchange',()=>{if(location.hash==='#home'||location.hash===''||location.hash==='#collections'||location.hash==='#gallery'||location.hash==='#about'||location.hash==='#contact'){page='home';activeCategory=null;render()}});
render();
